"""Utilities for reading generated training evaluation reports."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def load_json_report(path: str | Path) -> dict[str, Any]:
    """Load a JSON report generated by the training pipeline."""
    report_path = Path(path)
    if not report_path.exists():
        raise FileNotFoundError(f"Report not found: {report_path}")
    with report_path.open("r", encoding="utf-8") as file:
        data = json.load(file)
    if not isinstance(data, dict):
        raise ValueError(f"Report must contain a JSON object: {report_path}")
    return data


def load_metrics(base_dir: str | Path = ".") -> dict[str, Any]:
    """Load both NLP and Isolation Forest metrics from a training directory."""
    root = Path(base_dir)
    return {
        "nlp": load_json_report(root / "reports" / "metrics.json"),
        "isolation_forest": load_json_report(
            root / "reports" / "isolation_forest_metrics.json"
        ),
    }
