export const ErrorCodes = {
    
    // Authentication
    
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    AUTH_ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    AUTH_REFRESH_TOKEN_EXPIRED: "AUTH_REFRESH_TOKEN_EXPIRED",

    
    // Validation
    
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
    INVALID_QUERY_PARAMS: "INVALID_QUERY_PARAMS",

    
    // User
    
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_NOT_FOUND: "USER_NOT_FOUND",

    
    // Database
    
    DATABASE_ERROR: "DATABASE_ERROR",
    DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",

    
    // RabbitMQ
    
    RABBITMQ_CONNECTION_FAILED: "RABBITMQ_CONNECTION_FAILED",
    RABBITMQ_PUBLISH_FAILED: "RABBITMQ_PUBLISH_FAILED",
    RABBITMQ_CONSUMER_FAILED: "RABBITMQ_CONSUMER_FAILED",

    
    // Redis
    
    REDIS_CONNECTION_FAILED: "REDIS_CONNECTION_FAILED",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

    
    // AI Engine
    
    AI_ANALYSIS_FAILED: "AI_ANALYSIS_FAILED",
    AI_MODEL_TIMEOUT: "AI_MODEL_TIMEOUT",
    AI_SHADOW_ANALYSIS_FAILED: "AI_SHADOW_ANALYSIS_FAILED",

    
    // Security
    
    FORBIDDEN: "FORBIDDEN",
    UNAUTHORIZED: "UNAUTHORIZED",

    
    // Generic
    
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
} as const;