from typing import Dict, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
)


class ThreatMatrix(BaseModel):
    """
    Represents the aggregated intelligence and scoring document
    stored in MongoDB.
    """

    model_config = ConfigDict(
        extra="ignore",
        populate_by_name=True,
        protected_namespaces=(),
    )

    event_id: str = Field(
        ...,
        description="Unique identifier linking back to the ThreatEvent.",
    )

    correlation_id: str = Field(
        ...,
        description="Trace identifier for the request lifecycle.",
    )

    user_id: str = Field(
        ...,
        description="Identifier of the evaluated user.",
    )

    tier1_nlp_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Tier-1 NLP risk score.",
    )

    tier2_if_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Tier-2 Isolation Forest risk score.",
    )

    final_fusion_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Final fused risk score.",
    )

    shadow_queue_verdict: str = Field(
        ...,
        description="Verdict generated by the asynchronous shadow evaluation.",
    )

    shadow_queue_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score of the shadow verdict.",
    )

    action_taken: Literal[
        "ALLOW",
        "MONITOR",
        "SHADOW",
        "BLOCK",
    ] = Field(
        ...,
        description="Final enforcement action.",
    )

    processing_time_ms: int = Field(
        ...,
        ge=0,
        description="Total processing time in milliseconds.",
    )

    model_versions: Dict[str, str] = Field(
        ...,
        description="Mapping of model names to model versions.",
    )

    created_at: AwareDatetime = Field(
        ...,
        description="Timestamp when the threat matrix was created.",
    )